query Account {
  account {
    id
    first_name
    last_name
    name
    email
    phone
    birthday
    status
    avatar
    deleted
    created_at
  }
}

mutation UpdateName($input: UpdateNameInput!) {
  updateName(input: $input) {
    id
    first_name
    last_name
    name
    email
    phone
    birthday
    status
    avatar
    deleted
    created_at
  }
}

mutation ChangeEmail($input: ChangeEmailInput!) {
  changeEmail(input: $input) {
    id
    first_name
    last_name
    name
    email
    phone
    birthday
    status
    avatar
    deleted
    created_at
  }
}

mutation ChangePhone($input: ChangePhoneInput!) {
  changePhone(input: $input) {
    id
    first_name
    last_name
    name
    email
    phone
    birthday
    status
    avatar
    deleted
    created_at
  }
}
