mutation CreateAsistenti($input: CreateAsistent!) {
  createAsistenti(input: $input) {
    id
    emri
    mbiemri
    department {
      id
      emri_departmentit
      numri_i_zyreve
      deleted
      created_at
    }
  }
}

mutation UpdateAsistenti($input: UpdateAsistent!) {
  updateAsistenti(input: $input) {
    id
    emri
    mbiemri
    department {
      id
      emri_departmentit
      numri_i_zyreve
      deleted
      created_at
    }
  }
}

query Asistentet($input: GetAllAsistents!) {
  asistentet(input: $input) {
    id
    emri
    mbiemri
    department {
      id
      emri_departmentit
      numri_i_zyreve
      deleted
      created_at
    }
  }
}
