query Properties($input: GetAllPropertiesInput!) {
  properties(input: $input) {
    edges {
      cursor
      node {
        id
        short_id
        title
        category
        state {
          id
          name
          created_at
        }
        city {
          id
          name
          created_at
        }
        street {
          id
          name
          created_at
        }
        agent {
          id
          first_name
          last_name
          name
          email
          phone
          birthday
          status
          avatar
          created_at
        }
        surface
        sell_price
        rent_price
        for_sale
        for_rent
        deleted
        created_at
      }
    }
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
    search
  }
}

query PropertyDetails($input: GetPropertyInput!) {
  propertyDetails(input: $input) {
    id
    short_id
    title
    description
    category
    state {
      id
      name
      created_at
    }
    city {
      id
      name
      created_at
    }
    street {
      id
      name
      created_at
    }
    surface
    floor
    number_of_floors
    building_year
    number_of_rooms
    number_of_bathrooms
    number_of_bedrooms
    number_of_balconies
    sell_price
    rent_price
    for_sale
    for_rent
    images {
      id
      url
      type
      original_name
      mimetype
      order_number
    }
    agent {
      id
      first_name
      last_name
      name
      email
      phone
      birthday
      status
      avatar
      created_at
    }
    deleted
    created_at
  }
}

mutation CreateProperty($input: CreatePropertyInput!) {
  createProperty(input: $input) {
    id
    short_id
    title
    description
    category
    state {
      id
      name
      created_at
    }
    city {
      id
      name
      created_at
    }
    street {
      id
      name
      created_at
    }
    surface
    floor
    number_of_floors
    building_year
    number_of_rooms
    number_of_bathrooms
    number_of_bedrooms
    number_of_balconies
    sell_price
    rent_price
    for_sale
    for_rent
    images {
      id
      url
      type
      original_name
      mimetype
      order_number
    }
    agent {
      id
      first_name
      last_name
      name
      email
      phone
      birthday
      status
      avatar
      created_at
    }
    deleted
    created_at
  }
}

mutation UpdateProperty($input: UpdatePropertyInput!) {
  updateProperty(input: $input) {
    id
    short_id
    title
    description
    category
    state {
      id
      name
      created_at
    }
    city {
      id
      name
      created_at
    }
    street {
      id
      name
      created_at
    }
    surface
    floor
    number_of_floors
    building_year
    number_of_rooms
    number_of_bathrooms
    number_of_bedrooms
    number_of_balconies
    sell_price
    rent_price
    for_sale
    for_rent
    images {
      id
      url
      type
      original_name
      mimetype
      order_number
    }
    agent {
      id
      first_name
      last_name
      name
      email
      phone
      birthday
      status
      avatar
      created_at
    }
    deleted
    created_at
  }
}

mutation RemoveRestoreProperty($input: RemoveRestorePropertyInput!) {
  removeRestoreProperty(input: $input)
}

subscription PropertyCreated {
  propertyCreated {
    id
    short_id
    title
    description
    category
    state {
      id
      name
      created_at
    }
    city {
      id
      name
      created_at
    }
    street {
      id
      name
      created_at
    }
    surface
    floor
    number_of_floors
    building_year
    number_of_rooms
    number_of_bathrooms
    number_of_bedrooms
    number_of_balconies
    sell_price
    rent_price
    for_sale
    for_rent
    images {
      id
      url
      type
      original_name
      mimetype
      order_number
    }
    agent {
      id
      first_name
      last_name
      name
      email
      phone
      birthday
      status
      avatar
      created_at
    }
    deleted
    created_at
  }
}

subscription PropertyUpdated($input: GetPropertyInput!) {
  propertyUpdated(input: $input) {
    id
    short_id
    title
    description
    category
    state {
      id
      name
      created_at
    }
    city {
      id
      name
      created_at
    }
    street {
      id
      name
      created_at
    }
    surface
    floor
    number_of_floors
    building_year
    number_of_rooms
    number_of_bathrooms
    number_of_bedrooms
    number_of_balconies
    sell_price
    rent_price
    for_sale
    for_rent
    images {
      id
      url
      type
      original_name
      mimetype
      order_number
    }
    agent {
      id
      first_name
      last_name
      name
      email
      phone
      birthday
      status
      avatar
      created_at
    }
    deleted
    created_at
  }
}

subscription PropertyUpdatedList {
  propertyUpdatedList {
    id
    short_id
    title
    description
    category
    state {
      id
      name
      created_at
    }
    city {
      id
      name
      created_at
    }
    street {
      id
      name
      created_at
    }
    surface
    floor
    number_of_floors
    building_year
    number_of_rooms
    number_of_bathrooms
    number_of_bedrooms
    number_of_balconies
    sell_price
    rent_price
    for_sale
    for_rent
    images {
      id
      url
      type
      original_name
      mimetype
      order_number
    }
    agent {
      id
      first_name
      last_name
      name
      email
      phone
      birthday
      status
      avatar
      created_at
    }
    deleted
    created_at
  }
}

subscription PropertyRemovedRestore($input: RemoveRestorePropertyInput!) {
  propertyRemovedRestore(input: $input) {
    id
    short_id
    title
    description
    category
    state {
      id
      name
      created_at
    }
    city {
      id
      name
      created_at
    }
    street {
      id
      name
      created_at
    }
    surface
    floor
    number_of_floors
    building_year
    number_of_rooms
    number_of_bathrooms
    number_of_bedrooms
    number_of_balconies
    sell_price
    rent_price
    for_sale
    for_rent
    images {
      id
      url
      type
      original_name
      mimetype
      order_number
    }
    agent {
      id
      first_name
      last_name
      name
      email
      phone
      birthday
      status
      avatar
      created_at
    }
    deleted
    created_at
  }
}

subscription PropertyRemovedRestoreList {
  propertyRemovedRestoreList {
    id
    short_id
    title
    description
    category
    state {
      id
      name
      created_at
    }
    city {
      id
      name
      created_at
    }
    street {
      id
      name
      created_at
    }
    surface
    floor
    number_of_floors
    building_year
    number_of_rooms
    number_of_bathrooms
    number_of_bedrooms
    number_of_balconies
    sell_price
    rent_price
    for_sale
    for_rent
    images {
      id
      url
      type
      original_name
      mimetype
      order_number
    }
    agent {
      id
      first_name
      last_name
      name
      email
      phone
      birthday
      status
      avatar
      created_at
    }
    deleted
    created_at
  }
}

mutation ChangePropertyStatus($input: ChangePropertyStatusInput!) {
  changePropertyStatus(input: $input)
}

subscription PropertyStatusUpdated($input: GetPropertyInput!) {
  propertyStatusUpdated(input: $input) {
    id
    short_id
    title
    description
    category
    status
    state {
      id
      name
      created_at
    }
    city {
      id
      name
      created_at
    }
    street {
      id
      name
      created_at
    }
    surface
    floor
    number_of_floors
    building_year
    number_of_rooms
    number_of_bathrooms
    number_of_bedrooms
    number_of_balconies
    sell_price
    rent_price
    for_sale
    for_rent
    images {
      id
      url
      type
      original_name
      mimetype
      order_number
    }
    agent {
      id
      first_name
      last_name
      name
      email
      phone
      birthday
      status
      avatar
      created_at
    }
    client {
      id
      first_name
      last_name
      name
      email
      phone
      birthday
      status
      deleted
      created_at
    }
    deleted
    created_at
  }
}

subscription PropertyStatusUpdatedList {
  propertyStatusUpdatedList {
    id
    short_id
    title
    description
    category
    status
    state {
      id
      name
      created_at
    }
    city {
      id
      name
      created_at
    }
    street {
      id
      name
      created_at
    }
    surface
    floor
    number_of_floors
    building_year
    number_of_rooms
    number_of_bathrooms
    number_of_bedrooms
    number_of_balconies
    sell_price
    rent_price
    for_sale
    for_rent
    images {
      id
      url
      type
      original_name
      mimetype
      order_number
    }
    agent {
      id
      first_name
      last_name
      name
      email
      phone
      birthday
      status
      avatar
      created_at
    }
    client {
      id
      first_name
      last_name
      name
      email
      phone
      birthday
      status
      deleted
      created_at
    }
    deleted
    created_at
  }
}
